using System.Runtime.InteropServices;

namespace MooseEngine.Graphics.OpenGL;

public partial class GL
{
    internal class Delegates
    {
        internal delegate void glDrawRangeElementsDelegate(uint mode, uint start, uint end, int count, uint type, IntPtr indices);
        internal delegate void glTexImage3DDelegate(uint target, int level, int internalformat, int width, int height, int depth, int border, uint format, uint type, IntPtr pixels);
        internal delegate void glTexSubImage3DDelegate(uint target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, uint format, uint type, IntPtr pixels);
        internal delegate void glCopyTexSubImage3DDelegate(uint target, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height);
        internal delegate void glActiveTextureDelegate(uint texture);
        internal delegate void glSampleCoverageDelegate(float value, bool invert);
        internal delegate void glCompressedTexImage3DDelegate(uint target, int level, uint internalformat, int width, int height, int depth, int border, int imageSize, IntPtr data);
        internal delegate void glCompressedTexImage2DDelegate(uint target, int level, uint internalformat, int width, int height, int border, int imageSize, IntPtr data);
        internal delegate void glCompressedTexImage1DDelegate(uint target, int level, uint internalformat, int width, int border, int imageSize, IntPtr data);
        internal delegate void glCompressedTexSubImage3DDelegate(uint target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, uint format, int imageSize, IntPtr data);
        internal delegate void glCompressedTexSubImage2DDelegate(uint target, int level, int xoffset, int yoffset, int width, int height, uint format, int imageSize, IntPtr data);
        internal delegate void glCompressedTexSubImage1DDelegate(uint target, int level, int xoffset, int width, uint format, int imageSize, IntPtr data);
        internal delegate void glGetCompressedTexImageDelegate(uint target, int level, IntPtr img);
        internal delegate void glClientActiveTextureDelegate(uint texture);
        internal delegate void glMultiTexCoord1dDelegate(uint target, double s);
        internal delegate void glMultiTexCoord1dvDelegate(uint target, double[] v);
        internal delegate void glMultiTexCoord1fDelegate(uint target, float s);
        internal delegate void glMultiTexCoord1fvDelegate(uint target, float[] v);
        internal delegate void glMultiTexCoord1iDelegate(uint target, int s);
        internal delegate void glMultiTexCoord1ivDelegate(uint target, int[] v);
        internal delegate void glMultiTexCoord1sDelegate(uint target, short s);
        internal delegate void glMultiTexCoord1svDelegate(uint target, short[] v);
        internal delegate void glMultiTexCoord2dDelegate(uint target, double s, double t);
        internal delegate void glMultiTexCoord2dvDelegate(uint target, double[] v);
        internal delegate void glMultiTexCoord2fDelegate(uint target, float s, float t);
        internal delegate void glMultiTexCoord2fvDelegate(uint target, float[] v);
        internal delegate void glMultiTexCoord2iDelegate(uint target, int s, int t);
        internal delegate void glMultiTexCoord2ivDelegate(uint target, int[] v);
        internal delegate void glMultiTexCoord2sDelegate(uint target, short s, short t);
        internal delegate void glMultiTexCoord2svDelegate(uint target, short[] v);
        internal delegate void glMultiTexCoord3dDelegate(uint target, double s, double t, double r);
        internal delegate void glMultiTexCoord3dvDelegate(uint target, double[] v);
        internal delegate void glMultiTexCoord3fDelegate(uint target, float s, float t, float r);
        internal delegate void glMultiTexCoord3fvDelegate(uint target, float[] v);
        internal delegate void glMultiTexCoord3iDelegate(uint target, int s, int t, int r);
        internal delegate void glMultiTexCoord3ivDelegate(uint target, int[] v);
        internal delegate void glMultiTexCoord3sDelegate(uint target, short s, short t, short r);
        internal delegate void glMultiTexCoord3svDelegate(uint target, short[] v);
        internal delegate void glMultiTexCoord4dDelegate(uint target, double s, double t, double r, double q);
        internal delegate void glMultiTexCoord4dvDelegate(uint target, double[] v);
        internal delegate void glMultiTexCoord4fDelegate(uint target, float s, float t, float r, float q);
        internal delegate void glMultiTexCoord4fvDelegate(uint target, float[] v);
        internal delegate void glMultiTexCoord4iDelegate(uint target, int s, int t, int r, int q);
        internal delegate void glMultiTexCoord4ivDelegate(uint target, int[] v);
        internal delegate void glMultiTexCoord4sDelegate(uint target, short s, short t, short r, short q);
        internal delegate void glMultiTexCoord4svDelegate(uint target, short[] v);
        internal delegate void glLoadTransposeMatrixfDelegate(float[] m);
        internal delegate void glLoadTransposeMatrixdDelegate(double[] m);
        internal delegate void glMultTransposeMatrixfDelegate(float[] m);
        internal delegate void glMultTransposeMatrixdDelegate(double[] m);
        internal delegate void glBlendFuncSeparateDelegate(uint sfactorRGB, uint dfactorRGB, uint sfactorAlpha, uint dfactorAlpha);
        internal delegate void glMultiDrawArraysDelegate(uint mode, int[] first, int[] count, int drawcount);
        internal delegate void glMultiDrawElementsDelegate(uint mode, int[] count, uint type, IntPtr indices, int drawcount);
        internal delegate void glPointParameterfDelegate(uint pname, float param);
        internal delegate void glPointParameterfvDelegate(uint pname, float[] @params);
        internal delegate void glPointParameteriDelegate(uint pname, int param);
        internal delegate void glPointParameterivDelegate(uint pname, int[] @params);
        internal delegate void glFogCoordfDelegate(float coord);
        internal delegate void glFogCoordfvDelegate(float[] coord);
        internal delegate void glFogCoorddDelegate(double coord);
        internal delegate void glFogCoorddvDelegate(double[] coord);
        internal delegate void glFogCoordPointerDelegate(uint type, int stride, IntPtr pointer);
        internal delegate void glSecondaryColor3bDelegate(byte red, byte green, byte blue);
        internal delegate void glSecondaryColor3bvDelegate(byte[] v);
        internal delegate void glSecondaryColor3dDelegate(double red, double green, double blue);
        internal delegate void glSecondaryColor3dvDelegate(double[] v);
        internal delegate void glSecondaryColor3fDelegate(float red, float green, float blue);
        internal delegate void glSecondaryColor3fvDelegate(float[] v);
        internal delegate void glSecondaryColor3iDelegate(int red, int green, int blue);
        internal delegate void glSecondaryColor3ivDelegate(int[] v);
        internal delegate void glSecondaryColor3sDelegate(short red, short green, short blue);
        internal delegate void glSecondaryColor3svDelegate(short[] v);
        internal delegate void glSecondaryColor3ubDelegate(byte red, byte green, byte blue);
        internal delegate void glSecondaryColor3ubvDelegate(byte[] v);
        internal delegate void glSecondaryColor3uiDelegate(uint red, uint green, uint blue);
        internal delegate void glSecondaryColor3uivDelegate(uint[] v);
        internal delegate void glSecondaryColor3usDelegate(ushort red, ushort green, ushort blue);
        internal delegate void glSecondaryColor3usvDelegate(ushort[] v);
        internal delegate void glSecondaryColorPointerDelegate(int size, uint type, int stride, IntPtr pointer);
        internal delegate void glWindowPos2dDelegate(double x, double y);
        internal delegate void glWindowPos2dvDelegate(double[] v);
        internal delegate void glWindowPos2fDelegate(float x, float y);
        internal delegate void glWindowPos2fvDelegate(float[] v);
        internal delegate void glWindowPos2iDelegate(int x, int y);
        internal delegate void glWindowPos2ivDelegate(int[] v);
        internal delegate void glWindowPos2sDelegate(short x, short y);
        internal delegate void glWindowPos2svDelegate(short[] v);
        internal delegate void glWindowPos3dDelegate(double x, double y, double z);
        internal delegate void glWindowPos3dvDelegate(double[] v);
        internal delegate void glWindowPos3fDelegate(float x, float y, float z);
        internal delegate void glWindowPos3fvDelegate(float[] v);
        internal delegate void glWindowPos3iDelegate(int x, int y, int z);
        internal delegate void glWindowPos3ivDelegate(int[] v);
        internal delegate void glWindowPos3sDelegate(short x, short y, short z);
        internal delegate void glWindowPos3svDelegate(short[] v);
        internal delegate void glBlendColorDelegate(float red, float green, float blue, float alpha);
        internal delegate void glBlendEquationDelegate(uint mode);
        internal delegate void glGenQueriesDelegate(int n, uint[] ids);
        internal delegate void glDeleteQueriesDelegate(int n, uint[] ids);
        internal delegate bool glIsQueryDelegate(uint id);
        internal delegate void glBeginQueryDelegate(uint target, uint id);
        internal delegate void glEndQueryDelegate(uint target);
        internal delegate void glGetQueryivDelegate(uint target, uint pname, int[] @params);
        internal delegate void glGetQueryObjectivDelegate(uint id, uint pname, int[] @params);
        internal delegate void glGetQueryObjectuivDelegate(uint id, uint pname, uint[] @params);
        internal delegate void glBindBufferDelegate(uint target, uint buffer);
        internal delegate void glDeleteBuffersDelegate(int n, uint[] buffers);
        internal delegate void glGenBuffersDelegate(int n, uint[] buffers);
        internal delegate bool glIsBufferDelegate(uint buffer);

        // TODO: Testing
        internal unsafe delegate void glBufferDataUnsafeDelegate(uint target, int size, void* data, uint usage);
        internal delegate void glBufferDataDelegate(uint target, int size, IntPtr dataPtr, uint usage);
        internal unsafe delegate void glBufferSubDataUnsafeDelegate(uint target, int offset, int size, void* data);
        internal delegate void glBufferSubDataDelegate(uint target, int offset, int size, IntPtr dataPtr);

        internal delegate void glGetBufferSubDataDelegate(uint target, IntPtr offset, IntPtr size, IntPtr data);
        internal delegate void glMapBufferDelegate(uint target, uint access);
        internal delegate bool glUnmapBufferDelegate(uint target);
        internal delegate void glGetBufferParameterivDelegate(uint target, uint pname, int[] @params);
        internal delegate void glGetBufferPointervDelegate(uint target, uint pname, IntPtr @params);
        internal delegate void glBlendEquationSeparateDelegate(uint modeRGB, uint modeAlpha);
        internal delegate void glDrawBuffersDelegate(int n, uint[] bufs);
        internal delegate void glStencilOpSeparateDelegate(uint face, uint sfail, uint dpfail, uint dppass);
        internal delegate void glStencilFuncSeparateDelegate(uint face, uint func, int @ref, uint mask);
        internal delegate void glStencilMaskSeparateDelegate(uint face, uint mask);
        internal delegate void glAttachShaderDelegate(uint program, uint shader);
        internal delegate void glBindAttribLocationDelegate(uint program, uint index, string[] name);
        internal delegate void glCompileShaderDelegate(uint shader);
        internal delegate uint glCreateProgramDelegate();
        internal delegate uint glCreateShaderDelegate(uint type);
        internal delegate void glDeleteProgramDelegate(uint program);
        internal delegate void glDeleteShaderDelegate(uint shader);
        internal delegate void glDetachShaderDelegate(uint program, uint shader);
        internal delegate void glDisableVertexAttribArrayDelegate(uint index);
        internal delegate void glEnableVertexAttribArrayDelegate(uint index);
        internal delegate void glGetActiveAttribDelegate(uint program, uint index, int bufSize, int[] length, int[] size, uint[] type, string[] name);
        //internal delegate void glGetActiveUniformDelegate(uint program, uint index, int bufSize, int[] length, int[] size, uint[] type, string[] name);
        internal unsafe delegate void glGetActiveUniformDelegate(uint program, uint index, int bufSize, int* length, int* size, uint* type, char* name);
        internal delegate void glGetAttachedShadersDelegate(uint program, int maxCount, int[] count, uint[] shaders);
        internal delegate uint glGetAttribLocationDelegate(uint program, string name);
        internal delegate void glGetProgramivDelegate(uint program, uint pname, ref int @params);
        internal delegate void glGetProgramInfoLogDelegate(uint program, int bufSize, ref int length, byte[] infoLog);
        internal delegate void glGetShaderivDelegate(uint shader, uint pname, ref int @params);
        internal delegate void glGetShaderInfoLogDelegate(uint shader, int bufSize, ref int length, byte[] infoLog);
        internal delegate void glGetShaderSourceDelegate(uint shader, int bufSize, int[] length, char[] source);
        internal delegate uint glGetUniformLocationDelegate(uint program, string name);
        internal delegate void glGetUniformfvDelegate(uint program, uint location, float[] @params);
        internal delegate void glGetUniformivDelegate(uint program, uint location, int[] @params);
        internal delegate void glGetVertexAttribdvDelegate(uint index, uint pname, double[] @params);
        internal delegate void glGetVertexAttribfvDelegate(uint index, uint pname, float[] @params);
        internal delegate void glGetVertexAttribivDelegate(uint index, uint pname, int[] @params);
        internal delegate void glGetVertexAttribPointervDelegate(uint index, uint pname, IntPtr pointer);
        internal delegate bool glIsProgramDelegate(uint program);
        internal delegate bool glIsShaderDelegate(uint shader);
        internal delegate void glLinkProgramDelegate(uint program);
        [UnmanagedFunctionPointer(CallingConvention.StdCall, ThrowOnUnmappableChar = true)]
        internal delegate void glShaderSourceDelegate(uint shader, int count, string[] @string, int[] length);
        internal delegate void glUseProgramDelegate(uint program);
        internal delegate void glUniform1fDelegate(uint location, float v0);
        internal delegate void glUniform2fDelegate(uint location, float v0, float v1);
        internal delegate void glUniform3fDelegate(uint location, float v0, float v1, float v2);
        internal delegate void glUniform4fDelegate(uint location, float v0, float v1, float v2, float v3);
        internal delegate void glUniform1iDelegate(uint location, int v0);
        internal delegate void glUniform2iDelegate(uint location, int v0, int v1);
        internal delegate void glUniform3iDelegate(uint location, int v0, int v1, int v2);
        internal delegate void glUniform4iDelegate(uint location, int v0, int v1, int v2, int v3);
        internal delegate void glUniform1fvDelegate(uint location, int count, float[] value);
        internal delegate void glUniform2fvDelegate(uint location, int count, float[] value);
        internal delegate void glUniform3fvDelegate(uint location, int count, float[] value);
        internal delegate void glUniform4fvDelegate(uint location, int count, float[] value);
        internal delegate void glUniform1ivDelegate(uint location, int count, int[] value);
        internal delegate void glUniform2ivDelegate(uint location, int count, int[] value);
        internal delegate void glUniform3ivDelegate(uint location, int count, int[] value);
        internal delegate void glUniform4ivDelegate(uint location, int count, int[] value);
        internal delegate void glUniformMatrix2fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glUniformMatrix3fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glUniformMatrix4fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glValidateProgramDelegate(uint program);
        internal delegate void glVertexAttrib1dDelegate(uint index, double x);
        internal delegate void glVertexAttrib1dvDelegate(uint index, double[] v);
        internal delegate void glVertexAttrib1fDelegate(uint index, float x);
        internal delegate void glVertexAttrib1fvDelegate(uint index, float[] v);
        internal delegate void glVertexAttrib1sDelegate(uint index, short x);
        internal delegate void glVertexAttrib1svDelegate(uint index, short[] v);
        internal delegate void glVertexAttrib2dDelegate(uint index, double x, double y);
        internal delegate void glVertexAttrib2dvDelegate(uint index, double[] v);
        internal delegate void glVertexAttrib2fDelegate(uint index, float x, float y);
        internal delegate void glVertexAttrib2fvDelegate(uint index, float[] v);
        internal delegate void glVertexAttrib2sDelegate(uint index, short x, short y);
        internal delegate void glVertexAttrib2svDelegate(uint index, short[] v);
        internal delegate void glVertexAttrib3dDelegate(uint index, double x, double y, double z);
        internal delegate void glVertexAttrib3dvDelegate(uint index, double[] v);
        internal delegate void glVertexAttrib3fDelegate(uint index, float x, float y, float z);
        internal delegate void glVertexAttrib3fvDelegate(uint index, float[] v);
        internal delegate void glVertexAttrib3sDelegate(uint index, short x, short y, short z);
        internal delegate void glVertexAttrib3svDelegate(uint index, short[] v);
        internal delegate void glVertexAttrib4NbvDelegate(uint index, byte[] v);
        internal delegate void glVertexAttrib4NivDelegate(uint index, int[] v);
        internal delegate void glVertexAttrib4NsvDelegate(uint index, short[] v);
        internal delegate void glVertexAttrib4NubDelegate(uint index, byte x, byte y, byte z, byte w);
        internal delegate void glVertexAttrib4NubvDelegate(uint index, byte[] v);
        internal delegate void glVertexAttrib4NuivDelegate(uint index, uint[] v);
        internal delegate void glVertexAttrib4NusvDelegate(uint index, ushort[] v);
        internal delegate void glVertexAttrib4bvDelegate(uint index, byte[] v);
        internal delegate void glVertexAttrib4dDelegate(uint index, double x, double y, double z, double w);
        internal delegate void glVertexAttrib4dvDelegate(uint index, double[] v);
        internal delegate void glVertexAttrib4fDelegate(uint index, float x, float y, float z, float w);
        internal delegate void glVertexAttrib4fvDelegate(uint index, float[] v);
        internal delegate void glVertexAttrib4ivDelegate(uint index, int[] v);
        internal delegate void glVertexAttrib4sDelegate(uint index, short x, short y, short z, short w);
        internal delegate void glVertexAttrib4svDelegate(uint index, short[] v);
        internal delegate void glVertexAttrib4ubvDelegate(uint index, byte[] v);
        internal delegate void glVertexAttrib4uivDelegate(uint index, uint[] v);
        internal delegate void glVertexAttrib4usvDelegate(uint index, ushort[] v);
        internal delegate void glVertexAttribPointerDelegate(uint index, int size, uint type, bool normalized, int stride, IntPtr pointer);
        internal delegate void glReadPixelsDelegate(float x, float y, float width, float height, uint format, uint type, IntPtr pixels);
        internal delegate void glUniformMatrix2x3fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glUniformMatrix3x2fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glUniformMatrix2x4fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glUniformMatrix4x2fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glUniformMatrix3x4fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glUniformMatrix4x3fvDelegate(uint location, int count, bool transpose, float[] value);
        internal delegate void glColorMaskiDelegate(uint index, bool r, bool g, bool b, bool a);
        internal delegate void glGetBooleani_vDelegate(uint target, uint index, bool[] data);
        internal delegate void glGetIntegeri_vDelegate(uint target, uint index, int[] data);
        internal delegate void glEnableiDelegate(uint target, uint index);
        internal delegate void glDisableiDelegate(uint target, uint index);
        internal delegate bool glIsEnablediDelegate(uint target, uint index);
        internal delegate void glBeginTransformFeedbackDelegate(uint primitiveMode);
        internal delegate void glEndTransformFeedbackDelegate();
        internal delegate void glBindBufferRangeDelegate(uint target, uint index, uint buffer, IntPtr offset, IntPtr size);
        internal delegate void glBindBufferBaseDelegate(uint target, uint index, uint buffer);
        internal delegate void glTransformFeedbackVaryingsDelegate(uint program, int count, char[] varyings, uint bufferMode);
        internal delegate void glGetTransformFeedbackVaryingDelegate(uint program, uint index, int bufSize, int[] length, int[] size, uint[] type, char[] name);
        internal delegate void glClampColorDelegate(uint target, uint clamp);
        internal delegate void glBeginConditionalRenderDelegate(uint id, uint mode);
        internal delegate void glEndConditionalRenderDelegate();
        internal delegate void glVertexAttribIPointerDelegate(uint index, int size, uint type, int stride, IntPtr pointer);
        internal delegate void glGetVertexAttribIivDelegate(uint index, uint pname, int[] @params);
        internal delegate void glGetVertexAttribIuivDelegate(uint index, uint pname, uint[] @params);
        internal delegate void glVertexAttribI1iDelegate(uint index, int x);
        internal delegate void glVertexAttribI2iDelegate(uint index, int x, int y);
        internal delegate void glVertexAttribI3iDelegate(uint index, int x, int y, int z);
        internal delegate void glVertexAttribI4iDelegate(uint index, int x, int y, int z, int w);
        internal delegate void glVertexAttribI1uiDelegate(uint index, uint x);
        internal delegate void glVertexAttribI2uiDelegate(uint index, uint x, uint y);
        internal delegate void glVertexAttribI3uiDelegate(uint index, uint x, uint y, uint z);
        internal delegate void glVertexAttribI4uiDelegate(uint index, uint x, uint y, uint z, uint w);
        internal delegate void glVertexAttribI1ivDelegate(uint index, int[] v);
        internal delegate void glVertexAttribI2ivDelegate(uint index, int[] v);
        internal delegate void glVertexAttribI3ivDelegate(uint index, int[] v);
        internal delegate void glVertexAttribI4ivDelegate(uint index, int[] v);
        internal delegate void glVertexAttribI1uivDelegate(uint index, uint[] v);
        internal delegate void glVertexAttribI2uivDelegate(uint index, uint[] v);
        internal delegate void glVertexAttribI3uivDelegate(uint index, uint[] v);
        internal delegate void glVertexAttribI4uivDelegate(uint index, uint[] v);
        internal delegate void glVertexAttribI4bvDelegate(uint index, byte[] v);
        internal delegate void glVertexAttribI4svDelegate(uint index, short[] v);
        internal delegate void glVertexAttribI4ubvDelegate(uint index, byte[] v);
        internal delegate void glVertexAttribI4usvDelegate(uint index, ushort[] v);
        internal delegate void glGetUniformuivDelegate(uint program, uint location, uint[] @params);
        internal delegate void glBindFragDataLocationDelegate(uint program, uint color, char[] name);
        internal delegate int glGetFragDataLocationDelegate(uint program, char[] name);
        internal delegate void glUniform1uiDelegate(uint location, uint v0);
        internal delegate void glUniform2uiDelegate(uint location, uint v0, uint v1);
        internal delegate void glUniform3uiDelegate(uint location, uint v0, uint v1, uint v2);
        internal delegate void glUniform4uiDelegate(uint location, uint v0, uint v1, uint v2, uint v3);
        internal delegate void glUniform1uivDelegate(uint location, int count, uint[] value);
        internal delegate void glUniform2uivDelegate(uint location, int count, uint[] value);
        internal delegate void glUniform3uivDelegate(uint location, int count, uint[] value);
        internal delegate void glUniform4uivDelegate(uint location, int count, uint[] value);
        internal delegate void glTexParameterIivDelegate(uint target, uint pname, int[] @params);
        internal delegate void glTexParameterIuivDelegate(uint target, uint pname, uint[] @params);
        internal delegate void glGetTexParameterIivDelegate(uint target, uint pname, int[] @params);
        internal delegate void glGetTexParameterIuivDelegate(uint target, uint pname, uint[] @params);
        internal delegate void glClearBufferivDelegate(uint buffer, int drawbuffer, int[] value);
        internal delegate void glClearBufferuivDelegate(uint buffer, int drawbuffer, uint[] value);
        internal delegate void glClearBufferfvDelegate(uint buffer, int drawbuffer, float[] value);
        internal delegate void glClearBufferfiDelegate(uint buffer, int drawbuffer, float depth, int stencil);
        internal delegate bool glIsRenderbufferDelegate(uint renderbuffer);
        internal delegate void glBindRenderbufferDelegate(uint target, uint renderbuffer);
        internal delegate void glDeleteRenderbuffersDelegate(int n, uint[] renderbuffers);
        internal delegate void glGenRenderbuffersDelegate(int n, uint[] renderbuffers);
        internal delegate void glRenderbufferStorageDelegate(uint target, uint internalformat, int width, int height);
        internal delegate void glGetRenderbufferParameterivDelegate(uint target, uint pname, int[] @params);
        internal delegate bool glIsFramebufferDelegate(uint framebuffer);
        internal delegate void glBindFramebufferDelegate(uint target, uint framebuffer);
        internal delegate void glDeleteFramebuffersDelegate(int n, uint[] framebuffers);
        internal delegate void glGenFramebuffersDelegate(int n, uint[] framebuffers);
        internal delegate uint glCheckFramebufferStatusDelegate(uint target);
        internal delegate void glFramebufferTexture1DDelegate(uint target, uint attachment, uint textarget, uint texture, int level);
        internal delegate void glFramebufferTexture2DDelegate(uint target, uint attachment, uint textarget, uint texture, int level);
        internal delegate void glFramebufferTexture3DDelegate(uint target, uint attachment, uint textarget, uint texture, int level, int zoffset);
        internal delegate void glFramebufferRenderbufferDelegate(uint target, uint attachment, uint renderbuffertarget, uint renderbuffer);
        internal delegate void glGetFramebufferAttachmentParameterivDelegate(uint target, uint attachment, uint pname, int[] @params);
        internal delegate void glGenerateMipmapDelegate(uint target);
        internal delegate void glBlitFramebufferDelegate(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, uint mask, uint filter);
        internal delegate void glRenderbufferStorageMultisampleDelegate(uint target, int samples, uint internalformat, int width, int height);
        internal delegate void glFramebufferTextureLayerDelegate(uint target, uint attachment, uint texture, int level, int layer);
        internal delegate void glMapBufferRangeDelegate(uint target, IntPtr offset, IntPtr length, uint access);
        internal delegate void glFlushMappedBufferRangeDelegate(uint target, IntPtr offset, IntPtr length);
        internal delegate void glBindVertexArrayDelegate(uint array);
        internal delegate void glDeleteVertexArraysDelegate(int n, uint[] arrays);
        internal delegate void glGenVertexArraysDelegate(int n, uint[] arrays);
        internal delegate bool glIsVertexArrayDelegate(uint array);
        internal delegate void glDrawElementsBaseVertexDelegate(uint mode, int count, uint type, IntPtr indices, int basevertex);
        internal delegate void glDrawRangeElementsBaseVertexDelegate(uint mode, uint start, uint end, int count, uint type, IntPtr indices, int basevertex);
        internal delegate void glDrawElementsInstancedBaseVertexDelegate(uint mode, int count, uint type, IntPtr indices, int instancecount, int basevertex);
        internal delegate void glMultiDrawElementsBaseVertexDelegate(uint mode, int[] count, uint type, IntPtr indices, int drawcount, int[] basevertex);
        internal delegate void glProvokingVertexDelegate(uint mode);
        internal delegate IntPtr glFenceSyncDelegate(uint condition, uint flags);
        internal delegate bool glIsSyncDelegate(IntPtr sync);
        internal delegate void glDeleteSyncDelegate(IntPtr sync);
        internal delegate uint glClientWaitSyncDelegate(IntPtr sync, uint flags, UInt64 timeout);
        internal delegate void glWaitSyncDelegate(IntPtr sync, uint flags, UInt64 timeout);
        internal delegate void glGetInteger64vDelegate(uint pname, Int64[] data);
        internal delegate void glGetSyncivDelegate(IntPtr sync, uint pname, int bufSize, int[] length, int[] values);
        internal delegate void glGetInteger64i_vDelegate(uint target, uint index, Int64[] data);
        internal delegate void glGetBufferParameteri64vDelegate(uint target, uint pname, Int64[] @params);
        internal delegate void glFramebufferTextureDelegate(uint target, uint attachment, uint texture, int level);
        internal delegate void glTexImage2DMultisampleDelegate(uint target, int samples, uint internalformat, int width, int height, bool fixedsamplelocations);
        internal delegate void glTexImage3DMultisampleDelegate(uint target, int samples, uint internalformat, int width, int height, int depth, bool fixedsamplelocations);
        internal delegate void glGetMultisamplefvDelegate(uint pname, uint index, float[] val);
        internal delegate void glSampleMaskiDelegate(uint maskNumber, uint mask);
        internal delegate void glDrawArraysInstancedDelegate(uint mode, int first, int count, int instancecount);
        internal delegate void glDrawElementsInstancedDelegate(uint mode, int count, uint type, IntPtr indices, int instancecount);
        internal delegate void glTexBufferDelegate(uint target, uint internalformat, uint buffer);
        internal delegate void glPrimitiveRestartIndexDelegate(uint index);
        internal delegate void glCopyBufferSubDataDelegate(uint readTarget, uint writeTarget, IntPtr readOffset, IntPtr writeOffset, IntPtr size);
        internal delegate void glGetUniformIndicesDelegate(uint program, int uniformCount, char[] uniformNames, uint[] uniformIndices);
        internal delegate void glGetActiveUniformsivDelegate(uint program, int uniformCount, uint[] uniformIndices, uint pname, int[] @params);
        internal delegate void glGetActiveUniformNameDelegate(uint program, uint uniformIndex, int bufSize, int[] length, char[] uniformName);
        internal delegate uint glGetUniformBlockIndexDelegate(uint program, char[] uniformBlockName);
        internal delegate void glGetActiveUniformBlockivDelegate(uint program, uint uniformBlockIndex, uint pname, int[] @params);
        internal delegate void glGetActiveUniformBlockNameDelegate(uint program, uint uniformBlockIndex, int bufSize, int[] length, char[] uniformBlockName);
        internal delegate void glUniformBlockBindingDelegate(uint program, uint uniformBlockIndex, uint uniformBlockBinding);
        internal delegate void glBindFragDataLocationIndexedDelegate(uint program, uint colorNumber, uint index, char[] name);
        internal delegate int glGetFragDataIndexDelegate(uint program, char[] name);
        internal delegate void glGenSamplersDelegate(int count, uint[] samplers);
        internal delegate void glDeleteSamplersDelegate(int count, uint[] samplers);
        internal delegate bool glIsSamplerDelegate(uint sampler);
        internal delegate void glBindSamplerDelegate(uint unit, uint sampler);
        internal delegate void glSamplerParameteriDelegate(uint sampler, uint pname, int param);
        internal delegate void glSamplerParameterivDelegate(uint sampler, uint pname, int[] param);
        internal delegate void glSamplerParameterfDelegate(uint sampler, uint pname, float param);
        internal delegate void glSamplerParameterfvDelegate(uint sampler, uint pname, float[] param);
        internal delegate void glSamplerParameterIivDelegate(uint sampler, uint pname, int[] param);
        internal delegate void glSamplerParameterIuivDelegate(uint sampler, uint pname, uint[] param);
        internal delegate void glGetSamplerParameterivDelegate(uint sampler, uint pname, int[] @params);
        internal delegate void glGetSamplerParameterIivDelegate(uint sampler, uint pname, int[] @params);
        internal delegate void glGetSamplerParameterfvDelegate(uint sampler, uint pname, float[] @params);
        internal delegate void glGetSamplerParameterIuivDelegate(uint sampler, uint pname, uint[] @params);
        internal delegate void glQueryCounterDelegate(uint id, uint target);
        internal delegate void glGetQueryObjecti64vDelegate(uint id, uint pname, Int64[] @params);
        internal delegate void glGetQueryObjectui64vDelegate(uint id, uint pname, UInt64[] @params);
        internal delegate void glVertexAttribDivisorDelegate(uint index, uint divisor);
        internal delegate void glVertexAttribP1uiDelegate(uint index, uint type, bool normalized, uint value);
        internal delegate void glVertexAttribP1uivDelegate(uint index, uint type, bool normalized, uint[] value);
        internal delegate void glVertexAttribP2uiDelegate(uint index, uint type, bool normalized, uint value);
        internal delegate void glVertexAttribP2uivDelegate(uint index, uint type, bool normalized, uint[] value);
        internal delegate void glVertexAttribP3uiDelegate(uint index, uint type, bool normalized, uint value);
        internal delegate void glVertexAttribP3uivDelegate(uint index, uint type, bool normalized, uint[] value);
        internal delegate void glVertexAttribP4uiDelegate(uint index, uint type, bool normalized, uint value);
        internal delegate void glVertexAttribP4uivDelegate(uint index, uint type, bool normalized, uint[] value);
        internal delegate void glVertexP2uiDelegate(uint type, uint value);
        internal delegate void glVertexP2uivDelegate(uint type, uint[] value);
        internal delegate void glVertexP3uiDelegate(uint type, uint value);
        internal delegate void glVertexP3uivDelegate(uint type, uint[] value);
        internal delegate void glVertexP4uiDelegate(uint type, uint value);
        internal delegate void glVertexP4uivDelegate(uint type, uint[] value);
        internal delegate void glTexCoordP1uiDelegate(uint type, uint coords);
        internal delegate void glTexCoordP1uivDelegate(uint type, uint[] coords);
        internal delegate void glTexCoordP2uiDelegate(uint type, uint coords);
        internal delegate void glTexCoordP2uivDelegate(uint type, uint[] coords);
        internal delegate void glTexCoordP3uiDelegate(uint type, uint coords);
        internal delegate void glTexCoordP3uivDelegate(uint type, uint[] coords);
        internal delegate void glTexCoordP4uiDelegate(uint type, uint coords);
        internal delegate void glTexCoordP4uivDelegate(uint type, uint[] coords);
        internal delegate void glMultiTexCoordP1uiDelegate(uint texture, uint type, uint coords);
        internal delegate void glMultiTexCoordP1uivDelegate(uint texture, uint type, uint[] coords);
        internal delegate void glMultiTexCoordP2uiDelegate(uint texture, uint type, uint coords);
        internal delegate void glMultiTexCoordP2uivDelegate(uint texture, uint type, uint[] coords);
        internal delegate void glMultiTexCoordP3uiDelegate(uint texture, uint type, uint coords);
        internal delegate void glMultiTexCoordP3uivDelegate(uint texture, uint type, uint[] coords);
        internal delegate void glMultiTexCoordP4uiDelegate(uint texture, uint type, uint coords);
        internal delegate void glMultiTexCoordP4uivDelegate(uint texture, uint type, uint[] coords);
        internal delegate void glNormalP3uiDelegate(uint type, uint coords);
        internal delegate void glNormalP3uivDelegate(uint type, uint[] coords);
        internal delegate void glColorP3uiDelegate(uint type, uint color);
        internal delegate void glColorP3uivDelegate(uint type, uint[] color);
        internal delegate void glColorP4uiDelegate(uint type, uint color);
        internal delegate void glColorP4uivDelegate(uint type, uint[] color);
        internal delegate void glSecondaryColorP3uiDelegate(uint type, uint color);
        internal delegate void glSecondaryColorP3uivDelegate(uint type, uint[] color);
        internal delegate void glMinSampleShadingDelegate(float value);
        internal delegate void glBlendEquationiDelegate(uint buf, uint mode);
        internal delegate void glBlendEquationSeparateiDelegate(uint buf, uint modeRGB, uint modeAlpha);
        internal delegate void glBlendFunciDelegate(uint buf, uint src, uint dst);
        internal delegate void glBlendFuncSeparateiDelegate(uint buf, uint srcRGB, uint dstRGB, uint srcAlpha, uint dstAlpha);
        internal delegate void glDrawArraysIndirectDelegate(uint mode, IntPtr indirect);
        internal delegate void glDrawElementsIndirectDelegate(uint mode, uint type, IntPtr indirect);
        internal delegate void glUniform1dDelegate(uint location, double x);
        internal delegate void glUniform2dDelegate(uint location, double x, double y);
        internal delegate void glUniform3dDelegate(uint location, double x, double y, double z);
        internal delegate void glUniform4dDelegate(uint location, double x, double y, double z, double w);
        internal delegate void glUniform1dvDelegate(uint location, int count, double[] value);
        internal delegate void glUniform2dvDelegate(uint location, int count, double[] value);
        internal delegate void glUniform3dvDelegate(uint location, int count, double[] value);
        internal delegate void glUniform4dvDelegate(uint location, int count, double[] value);
        internal delegate void glUniformMatrix2dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glUniformMatrix3dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glUniformMatrix4dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glUniformMatrix2x3dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glUniformMatrix2x4dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glUniformMatrix3x2dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glUniformMatrix3x4dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glUniformMatrix4x2dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glUniformMatrix4x3dvDelegate(uint location, int count, bool transpose, double[] value);
        internal delegate void glGetUniformdvDelegate(uint program, uint location, double[] @params);
        internal delegate int glGetSubroutineUniformLocationDelegate(uint program, uint shadertype, char[] name);
        internal delegate uint glGetSubroutineIndexDelegate(uint program, uint shadertype, char[] name);
        internal delegate void glGetActiveSubroutineUniformivDelegate(uint program, uint shadertype, uint index, uint pname, int[] values);
        internal delegate void glGetActiveSubroutineUniformNameDelegate(uint program, uint shadertype, uint index, int bufsize, int[] length, char[] name);
        internal delegate void glGetActiveSubroutineNameDelegate(uint program, uint shadertype, uint index, int bufsize, int[] length, char[] name);
        internal delegate void glUniformSubroutinesuivDelegate(uint shadertype, int count, uint[] indices);
        internal delegate void glGetUniformSubroutineuivDelegate(uint shadertype, uint location, uint[] @params);
        internal delegate void glGetProgramStageivDelegate(uint program, uint shadertype, uint pname, int[] values);
        internal delegate void glPatchParameteriDelegate(uint pname, int value);
        internal delegate void glPatchParameterfvDelegate(uint pname, float[] values);
        internal delegate void glBindTransformFeedbackDelegate(uint target, uint id);
        internal delegate void glDeleteTransformFeedbacksDelegate(int n, uint[] ids);
        internal delegate void glGenTransformFeedbacksDelegate(int n, uint[] ids);
        internal delegate bool glIsTransformFeedbackDelegate(uint id);
        internal delegate void glPauseTransformFeedbackDelegate();
        internal delegate void glResumeTransformFeedbackDelegate();
        internal delegate void glDrawTransformFeedbackDelegate(uint mode, uint id);
        internal delegate void glDrawTransformFeedbackStreamDelegate(uint mode, uint id, uint stream);
        internal delegate void glBeginQueryIndexedDelegate(uint target, uint index, uint id);
        internal delegate void glEndQueryIndexedDelegate(uint target, uint index);
        internal delegate void glGetQueryIndexedivDelegate(uint target, uint index, uint pname, int[] @params);
        internal delegate void glReleaseShaderCompilerDelegate();
        internal delegate void glShaderBinaryDelegate(int count, uint[] shaders, uint binaryformat, IntPtr binary, int length);
        internal delegate void glGetShaderPrecisionFormatDelegate(uint shadertype, uint precisiontype, int[] range, int[] precision);
        internal delegate void glDepthRangefDelegate(float n, float f);
        internal delegate void glClearDepthfDelegate(float d);
        internal delegate void glGetProgramBinaryDelegate(uint program, int bufSize, int[] length, uint[] binaryFormat, IntPtr binary);
        internal delegate void glProgramBinaryDelegate(uint program, uint binaryFormat, IntPtr binary, int length);
        internal delegate void glProgramParameteriDelegate(uint program, uint pname, int value);
        internal delegate void glUseProgramStagesDelegate(uint pipeline, uint stages, uint program);
        internal delegate void glActiveShaderProgramDelegate(uint pipeline, uint program);
        internal delegate uint glCreateShaderProgramvDelegate(uint type, int count, char[] strings);
        internal delegate void glBindProgramPipelineDelegate(uint pipeline);
        internal delegate void glDeleteProgramPipelinesDelegate(int n, uint[] pipelines);
        internal delegate void glGenProgramPipelinesDelegate(int n, uint[] pipelines);
        internal delegate bool glIsProgramPipelineDelegate(uint pipeline);
        internal delegate void glGetProgramPipelineivDelegate(uint pipeline, uint pname, int[] @params);
        internal delegate void glProgramUniform1iDelegate(uint program, uint location, int v0);
        internal delegate void glProgramUniform1ivDelegate(uint program, uint location, int count, int[] value);
        internal delegate void glProgramUniform1fDelegate(uint program, uint location, float v0);
        internal delegate void glProgramUniform1fvDelegate(uint program, uint location, int count, float[] value);
        internal delegate void glProgramUniform1dDelegate(uint program, uint location, double v0);
        internal delegate void glProgramUniform1dvDelegate(uint program, uint location, int count, double[] value);
        internal delegate void glProgramUniform1uiDelegate(uint program, uint location, uint v0);
        internal delegate void glProgramUniform1uivDelegate(uint program, uint location, int count, uint[] value);
        internal delegate void glProgramUniform2iDelegate(uint program, uint location, int v0, int v1);
        internal delegate void glProgramUniform2ivDelegate(uint program, uint location, int count, int[] value);
        internal delegate void glProgramUniform2fDelegate(uint program, uint location, float v0, float v1);
        internal delegate void glProgramUniform2fvDelegate(uint program, uint location, int count, float[] value);
        internal delegate void glProgramUniform2dDelegate(uint program, uint location, double v0, double v1);
        internal delegate void glProgramUniform2dvDelegate(uint program, uint location, int count, double[] value);
        internal delegate void glProgramUniform2uiDelegate(uint program, uint location, uint v0, uint v1);
        internal delegate void glProgramUniform2uivDelegate(uint program, uint location, int count, uint[] value);
        internal delegate void glProgramUniform3iDelegate(uint program, uint location, int v0, int v1, int v2);
        internal delegate void glProgramUniform3ivDelegate(uint program, uint location, int count, int[] value);
        internal delegate void glProgramUniform3fDelegate(uint program, uint location, float v0, float v1, float v2);
        internal delegate void glProgramUniform3fvDelegate(uint program, uint location, int count, float[] value);
        internal delegate void glProgramUniform3dDelegate(uint program, uint location, double v0, double v1, double v2);
        internal delegate void glProgramUniform3dvDelegate(uint program, uint location, int count, double[] value);
        internal delegate void glProgramUniform3uiDelegate(uint program, uint location, uint v0, uint v1, uint v2);
        internal delegate void glProgramUniform3uivDelegate(uint program, uint location, int count, uint[] value);
        internal delegate void glProgramUniform4iDelegate(uint program, uint location, int v0, int v1, int v2, int v3);
        internal delegate void glProgramUniform4ivDelegate(uint program, uint location, int count, int[] value);
        internal delegate void glProgramUniform4fDelegate(uint program, uint location, float v0, float v1, float v2, float v3);
        internal delegate void glProgramUniform4fvDelegate(uint program, uint location, int count, float[] value);
        internal delegate void glProgramUniform4dDelegate(uint program, uint location, double v0, double v1, double v2, double v3);
        internal delegate void glProgramUniform4dvDelegate(uint program, uint location, int count, double[] value);
        internal delegate void glProgramUniform4uiDelegate(uint program, uint location, uint v0, uint v1, uint v2, uint v3);
        internal delegate void glProgramUniform4uivDelegate(uint program, uint location, int count, uint[] value);
        internal delegate void glProgramUniformMatrix2fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix3fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix4fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix2dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glProgramUniformMatrix3dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glProgramUniformMatrix4dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glProgramUniformMatrix2x3fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix3x2fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix2x4fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix4x2fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix3x4fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix4x3fvDelegate(uint program, uint location, int count, bool transpose, float[] value);
        internal delegate void glProgramUniformMatrix2x3dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glProgramUniformMatrix3x2dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glProgramUniformMatrix2x4dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glProgramUniformMatrix4x2dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glProgramUniformMatrix3x4dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glProgramUniformMatrix4x3dvDelegate(uint program, uint location, int count, bool transpose, double[] value);
        internal delegate void glValidateProgramPipelineDelegate(uint pipeline);
        internal delegate void glGetProgramPipelineInfoLogDelegate(uint pipeline, int bufSize, int[] length, char[] infoLog);
        internal delegate void glVertexAttribL1dDelegate(uint index, double x);
        internal delegate void glVertexAttribL2dDelegate(uint index, double x, double y);
        internal delegate void glVertexAttribL3dDelegate(uint index, double x, double y, double z);
        internal delegate void glVertexAttribL4dDelegate(uint index, double x, double y, double z, double w);
        internal delegate void glVertexAttribL1dvDelegate(uint index, double[] v);
        internal delegate void glVertexAttribL2dvDelegate(uint index, double[] v);
        internal delegate void glVertexAttribL3dvDelegate(uint index, double[] v);
        internal delegate void glVertexAttribL4dvDelegate(uint index, double[] v);
        internal delegate void glVertexAttribLPointerDelegate(uint index, int size, uint type, int stride, IntPtr pointer);
        internal delegate void glGetVertexAttribLdvDelegate(uint index, uint pname, double[] @params);
        internal delegate void glViewportArrayvDelegate(uint first, int count, float[] v);
        internal delegate void glViewportIndexedfDelegate(uint index, float x, float y, float w, float h);
        internal delegate void glViewportIndexedfvDelegate(uint index, float[] v);
        internal delegate void glScissorArrayvDelegate(uint first, int count, int[] v);
        internal delegate void glScissorIndexedDelegate(uint index, int left, int bottom, int width, int height);
        internal delegate void glScissorIndexedvDelegate(uint index, int[] v);
        internal delegate void glDepthRangeArrayvDelegate(uint first, int count, double[] v);
        internal delegate void glDepthRangeIndexedDelegate(uint index, double n, double f);
        internal delegate void glGetFloati_vDelegate(uint target, uint index, float[] data);
        internal delegate void glGetDoublei_vDelegate(uint target, uint index, double[] data);
        internal delegate void glDrawArraysInstancedBaseInstanceDelegate(uint mode, int first, int count, int instancecount, uint baseinstance);
        internal delegate void glDrawElementsInstancedBaseInstanceDelegate(uint mode, int count, uint type, IntPtr indices, int instancecount, uint baseinstance);
        internal delegate void glDrawElementsInstancedBaseVertexBaseInstanceDelegate(uint mode, int count, uint type, IntPtr indices, int instancecount, int basevertex, uint baseinstance);
        internal delegate void glGetInternalformativDelegate(uint target, uint internalformat, uint pname, int bufSize, int[] @params);
        internal delegate void glGetActiveAtomicCounterBufferivDelegate(uint program, uint bufferIndex, uint pname, int[] @params);
        internal delegate void glBindImageTextureDelegate(uint unit, uint texture, int level, bool layered, int layer, uint access, uint format);
        internal delegate void glMemoryBarrierDelegate(uint barriers);
        internal delegate void glTexStorage1DDelegate(uint target, int levels, uint internalformat, int width);
        internal delegate void glTexStorage2DDelegate(uint target, int levels, uint internalformat, int width, int height);
        internal delegate void glTexStorage3DDelegate(uint target, int levels, uint internalformat, int width, int height, int depth);
        internal delegate void glDrawTransformFeedbackInstancedDelegate(uint mode, uint id, int instancecount);
        internal delegate void glDrawTransformFeedbackStreamInstancedDelegate(uint mode, uint id, uint stream, int instancecount);
        internal delegate void glClearBufferDataDelegate(uint target, uint internalformat, uint format, uint type, IntPtr data);
        internal delegate void glClearBufferSubDataDelegate(uint target, uint internalformat, IntPtr offset, IntPtr size, uint format, uint type, IntPtr data);
        internal delegate void glDispatchComputeDelegate(uint num_groups_x, uint num_groups_y, uint num_groups_z);
        internal delegate void glDispatchComputeIndirectDelegate(IntPtr indirect);
        internal delegate void glCopyImageSubDataDelegate(uint srcName, uint srcTarget, int srcLevel, int srcX, int srcY, int srcZ, uint dstName, uint dstTarget, int dstLevel, int dstX, int dstY, int dstZ, int srcWidth, int srcHeight, int srcDepth);
        internal delegate void glFramebufferParameteriDelegate(uint target, uint pname, int param);
        internal delegate void glGetFramebufferParameterivDelegate(uint target, uint pname, int[] @params);
        internal delegate void glGetInternalformati64vDelegate(uint target, uint internalformat, uint pname, int bufSize, Int64[] @params);
        internal delegate void glInvalidateTexSubImageDelegate(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth);
        internal delegate void glInvalidateTexImageDelegate(uint texture, int level);
        internal delegate void glInvalidateBufferSubDataDelegate(uint buffer, IntPtr offset, IntPtr length);
        internal delegate void glInvalidateBufferDataDelegate(uint buffer);
        internal delegate void glInvalidateFramebufferDelegate(uint target, int numAttachments, uint[] attachments);
        internal delegate void glInvalidateSubFramebufferDelegate(uint target, int numAttachments, uint[] attachments, int x, int y, int width, int height);
        internal delegate void glMultiDrawArraysIndirectDelegate(uint mode, IntPtr indirect, int drawcount, int stride);
        internal delegate void glMultiDrawElementsIndirectDelegate(uint mode, uint type, IntPtr indirect, int drawcount, int stride);
        internal delegate void glGetProgramInterfaceivDelegate(uint program, uint programInterface, uint pname, int[] @params);
        internal delegate uint glGetProgramResourceIndexDelegate(uint program, uint programInterface, char[] name);
        internal delegate void glGetProgramResourceNameDelegate(uint program, uint programInterface, uint index, int bufSize, int[] length, char[] name);
        internal delegate void glGetProgramResourceivDelegate(uint program, uint programInterface, uint index, int propCount, uint[] props, int bufSize, int[] length, int[] @params);
        internal delegate int glGetProgramResourceLocationDelegate(uint program, uint programInterface, char[] name);
        internal delegate int glGetProgramResourceLocationIndexDelegate(uint program, uint programInterface, char[] name);
        internal delegate void glShaderStorageBlockBindingDelegate(uint program, uint storageBlockIndex, uint storageBlockBinding);
        internal delegate void glTexBufferRangeDelegate(uint target, uint internalformat, uint buffer, IntPtr offset, IntPtr size);
        internal delegate void glTexStorage2DMultisampleDelegate(uint target, int samples, uint internalformat, int width, int height, bool fixedsamplelocations);
        internal delegate void glTexStorage3DMultisampleDelegate(uint target, int samples, uint internalformat, int width, int height, int depth, bool fixedsamplelocations);
        internal delegate void glTextureViewDelegate(uint texture, uint target, uint origtexture, uint internalformat, uint minlevel, uint numlevels, uint minlayer, uint numlayers);
        internal delegate void glBindVertexBufferDelegate(uint bindingindex, uint buffer, IntPtr offset, int stride);
        internal delegate void glVertexAttribFormatDelegate(uint attribindex, int size, uint type, bool normalized, uint relativeoffset);
        internal delegate void glVertexAttribIFormatDelegate(uint attribindex, int size, uint type, uint relativeoffset);
        internal delegate void glVertexAttribLFormatDelegate(uint attribindex, int size, uint type, uint relativeoffset);
        internal delegate void glVertexAttribBindingDelegate(uint attribindex, uint bindingindex);
        internal delegate void glVertexBindingDivisorDelegate(uint bindingindex, uint divisor);
        internal delegate void glDebugMessageControlDelegate(uint source, uint type, uint severity, int count, uint[] ids, bool enabled);
        internal delegate void glDebugMessageInsertDelegate(uint source, uint type, uint id, uint severity, int length, char[] buf);
        internal delegate void glDebugMessageCallbackDelegate(IntPtr callback, IntPtr userParam);
        internal delegate uint glGetDebugMessageLogDelegate(uint count, int bufSize, uint[] sources, uint[] types, uint[] ids, uint[] severities, int[] lengths, char[] messageLog);
        internal delegate void glPushDebugGroupDelegate(uint source, uint id, int length, char[] message);
        internal delegate void glPopDebugGroupDelegate();
        internal delegate void glObjectLabelDelegate(uint identifier, uint name, int length, char[] label);
        internal delegate void glGetObjectLabelDelegate(uint identifier, uint name, int bufSize, int[] length, char[] label);
        internal delegate void glObjectPtrLabelDelegate(IntPtr ptr, int length, char[] label);
        internal delegate void glGetObjectPtrLabelDelegate(IntPtr ptr, int bufSize, int[] length, char[] label);
        internal delegate void glGetPointervDelegate(uint pname, IntPtr @params);
        internal delegate void glBufferStorageDelegate(uint target, IntPtr size, IntPtr data, uint flags);
        internal delegate void glClearTexImageDelegate(uint texture, int level, uint format, uint type, IntPtr data);
        internal delegate void glClearTexSubImageDelegate(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, uint format, uint type, IntPtr data);
        internal delegate void glBindBuffersBaseDelegate(uint target, uint first, int count, uint[] buffers);
        internal delegate void glBindBuffersRangeDelegate(uint target, uint first, int count, uint[] buffers, IntPtr offsets, IntPtr sizes);
        internal delegate void glBindTexturesDelegate(uint first, int count, uint[] textures);
        internal delegate void glBindSamplersDelegate(uint first, int count, uint[] samplers);
        internal delegate void glBindImageTexturesDelegate(uint first, int count, uint[] textures);
        internal delegate void glBindVertexBuffersDelegate(uint first, int count, uint[] buffers, IntPtr offsets, int[] strides);
        internal delegate void glClipControlDelegate(uint origin, uint depth);
        internal delegate void glCreateTransformFeedbacksDelegate(int n, uint[] ids);
        internal delegate void glTransformFeedbackBufferBaseDelegate(uint xfb, uint index, uint buffer);
        internal delegate void glTransformFeedbackBufferRangeDelegate(uint xfb, uint index, uint buffer, IntPtr offset, IntPtr size);
        internal delegate void glGetTransformFeedbackivDelegate(uint xfb, uint pname, int[] param);
        internal delegate void glGetTransformFeedbacki_vDelegate(uint xfb, uint pname, uint index, int[] param);
        internal delegate void glGetTransformFeedbacki64_vDelegate(uint xfb, uint pname, uint index, Int64[] param);
        internal delegate void glCreateBuffersDelegate(int n, uint[] buffers);
        internal delegate void glNamedBufferStorageDelegate(uint buffer, IntPtr size, IntPtr data, uint flags);
        internal delegate void glNamedBufferDataDelegate(uint buffer, IntPtr size, IntPtr data, uint usage);
        internal delegate void glNamedBufferSubDataDelegate(uint buffer, IntPtr offset, IntPtr size, IntPtr data);
        internal delegate void glCopyNamedBufferSubDataDelegate(uint readBuffer, uint writeBuffer, IntPtr readOffset, IntPtr writeOffset, IntPtr size);
        internal delegate void glClearNamedBufferDataDelegate(uint buffer, uint internalformat, uint format, uint type, IntPtr data);
        internal delegate void glClearNamedBufferSubDataDelegate(uint buffer, uint internalformat, IntPtr offset, IntPtr size, uint format, uint type, IntPtr data);
        internal delegate void glMapNamedBufferDelegate(uint buffer, uint access);
        internal delegate void glMapNamedBufferRangeDelegate(uint buffer, IntPtr offset, IntPtr length, uint access);
        internal delegate bool glUnmapNamedBufferDelegate(uint buffer);
        internal delegate void glFlushMappedNamedBufferRangeDelegate(uint buffer, IntPtr offset, IntPtr length);
        internal delegate void glGetNamedBufferParameterivDelegate(uint buffer, uint pname, int[] @params);
        internal delegate void glGetNamedBufferParameteri64vDelegate(uint buffer, uint pname, Int64[] @params);
        internal delegate void glGetNamedBufferPointervDelegate(uint buffer, uint pname, IntPtr @params);
        internal delegate void glGetNamedBufferSubDataDelegate(uint buffer, IntPtr offset, IntPtr size, IntPtr data);
        internal delegate void glCreateFramebuffersDelegate(int n, uint[] framebuffers);
        internal delegate void glNamedFramebufferRenderbufferDelegate(uint framebuffer, uint attachment, uint renderbuffertarget, uint renderbuffer);
        internal delegate void glNamedFramebufferParameteriDelegate(uint framebuffer, uint pname, int param);
        internal delegate void glNamedFramebufferTextureDelegate(uint framebuffer, uint attachment, uint texture, int level);
        internal delegate void glNamedFramebufferTextureLayerDelegate(uint framebuffer, uint attachment, uint texture, int level, int layer);
        internal delegate void glNamedFramebufferDrawBufferDelegate(uint framebuffer, uint buf);
        internal delegate void glNamedFramebufferDrawBuffersDelegate(uint framebuffer, int n, uint[] bufs);
        internal delegate void glNamedFramebufferReadBufferDelegate(uint framebuffer, uint src);
        internal delegate void glInvalidateNamedFramebufferDataDelegate(uint framebuffer, int numAttachments, uint[] attachments);
        internal delegate void glInvalidateNamedFramebufferSubDataDelegate(uint framebuffer, int numAttachments, uint[] attachments, int x, int y, int width, int height);
        internal delegate void glClearNamedFramebufferivDelegate(uint framebuffer, uint buffer, int drawbuffer, int[] value);
        internal delegate void glClearNamedFramebufferuivDelegate(uint framebuffer, uint buffer, int drawbuffer, uint[] value);
        internal delegate void glClearNamedFramebufferfvDelegate(uint framebuffer, uint buffer, int drawbuffer, float[] value);
        internal delegate void glClearNamedFramebufferfiDelegate(uint framebuffer, uint buffer, int drawbuffer, float depth, int stencil);
        internal delegate void glBlitNamedFramebufferDelegate(uint readFramebuffer, uint drawFramebuffer, int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, uint mask, uint filter);
        internal delegate uint glCheckNamedFramebufferStatusDelegate(uint framebuffer, uint target);
        internal delegate void glGetNamedFramebufferParameterivDelegate(uint framebuffer, uint pname, int[] param);
        internal delegate void glGetNamedFramebufferAttachmentParameterivDelegate(uint framebuffer, uint attachment, uint pname, int[] @params);
        internal delegate void glCreateRenderbuffersDelegate(int n, uint[] renderbuffers);
        internal delegate void glNamedRenderbufferStorageDelegate(uint renderbuffer, uint internalformat, int width, int height);
        internal delegate void glNamedRenderbufferStorageMultisampleDelegate(uint renderbuffer, int samples, uint internalformat, int width, int height);
        internal delegate void glGetNamedRenderbufferParameterivDelegate(uint renderbuffer, uint pname, int[] @params);
        internal delegate void glCreateTexturesDelegate(uint target, int n, uint[] textures);
        internal delegate void glTextureBufferDelegate(uint texture, uint internalformat, uint buffer);
        internal delegate void glTextureBufferRangeDelegate(uint texture, uint internalformat, uint buffer, IntPtr offset, IntPtr size);
        internal delegate void glTextureStorage1DDelegate(uint texture, int levels, uint internalformat, int width);
        internal delegate void glTextureStorage2DDelegate(uint texture, int levels, uint internalformat, int width, int height);
        internal delegate void glTextureStorage3DDelegate(uint texture, int levels, uint internalformat, int width, int height, int depth);
        internal delegate void glTextureStorage2DMultisampleDelegate(uint texture, int samples, uint internalformat, int width, int height, bool fixedsamplelocations);
        internal delegate void glTextureStorage3DMultisampleDelegate(uint texture, int samples, uint internalformat, int width, int height, int depth, bool fixedsamplelocations);
        internal delegate void glTextureSubImage1DDelegate(uint texture, int level, int xoffset, int width, uint format, uint type, IntPtr pixels);
        internal delegate void glTextureSubImage2DDelegate(uint texture, int level, int xoffset, int yoffset, int width, int height, uint format, uint type, IntPtr pixels);
        internal delegate void glTextureSubImage3DDelegate(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, uint format, uint type, IntPtr pixels);
        internal delegate void glCompressedTextureSubImage1DDelegate(uint texture, int level, int xoffset, int width, uint format, int imageSize, IntPtr data);
        internal delegate void glCompressedTextureSubImage2DDelegate(uint texture, int level, int xoffset, int yoffset, int width, int height, uint format, int imageSize, IntPtr data);
        internal delegate void glCompressedTextureSubImage3DDelegate(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, uint format, int imageSize, IntPtr data);
        internal delegate void glCopyTextureSubImage1DDelegate(uint texture, int level, int xoffset, int x, int y, int width);
        internal delegate void glCopyTextureSubImage2DDelegate(uint texture, int level, int xoffset, int yoffset, int x, int y, int width, int height);
        internal delegate void glCopyTextureSubImage3DDelegate(uint texture, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height);
        internal delegate void glTextureParameterfDelegate(uint texture, uint pname, float param);
        internal delegate void glTextureParameterfvDelegate(uint texture, uint pname, float[] param);
        internal delegate void glTextureParameteriDelegate(uint texture, uint pname, int param);
        internal delegate void glTextureParameterIivDelegate(uint texture, uint pname, int[] @params);
        internal delegate void glTextureParameterIuivDelegate(uint texture, uint pname, uint[] @params);
        internal delegate void glTextureParameterivDelegate(uint texture, uint pname, int[] param);
        internal delegate void glGenerateTextureMipmapDelegate(uint texture);
        internal delegate void glBindTextureUnitDelegate(uint unit, uint texture);
        internal delegate void glGetTextureImageDelegate(uint texture, int level, uint format, uint type, int bufSize, IntPtr pixels);
        internal delegate void glGetCompressedTextureImageDelegate(uint texture, int level, int bufSize, IntPtr pixels);
        internal delegate void glGetTextureLevelParameterfvDelegate(uint texture, int level, uint pname, float[] @params);
        internal delegate void glGetTextureLevelParameterivDelegate(uint texture, int level, uint pname, int[] @params);
        internal delegate void glGetTextureParameterfvDelegate(uint texture, uint pname, float[] @params);
        internal delegate void glGetTextureParameterIivDelegate(uint texture, uint pname, int[] @params);
        internal delegate void glGetTextureParameterIuivDelegate(uint texture, uint pname, uint[] @params);
        internal delegate void glGetTextureParameterivDelegate(uint texture, uint pname, int[] @params);
        internal delegate void glCreateVertexArraysDelegate(int n, uint[] arrays);
        internal delegate void glDisableVertexArrayAttribDelegate(uint vaobj, uint index);
        internal delegate void glEnableVertexArrayAttribDelegate(uint vaobj, uint index);
        internal delegate void glVertexArrayElementBufferDelegate(uint vaobj, uint buffer);
        internal delegate void glVertexArrayVertexBufferDelegate(uint vaobj, uint bindingindex, uint buffer, IntPtr offset, int stride);
        internal delegate void glVertexArrayVertexBuffersDelegate(uint vaobj, uint first, int count, uint[] buffers, IntPtr offsets, int[] strides);
        internal delegate void glVertexArrayAttribBindingDelegate(uint vaobj, uint attribindex, uint bindingindex);
        internal delegate void glVertexArrayAttribFormatDelegate(uint vaobj, uint attribindex, int size, uint type, bool normalized, uint relativeoffset);
        internal delegate void glVertexArrayAttribIFormatDelegate(uint vaobj, uint attribindex, int size, uint type, uint relativeoffset);
        internal delegate void glVertexArrayAttribLFormatDelegate(uint vaobj, uint attribindex, int size, uint type, uint relativeoffset);
        internal delegate void glVertexArrayBindingDivisorDelegate(uint vaobj, uint bindingindex, uint divisor);
        internal delegate void glGetVertexArrayivDelegate(uint vaobj, uint pname, int[] param);
        internal delegate void glGetVertexArrayIndexedivDelegate(uint vaobj, uint index, uint pname, int[] param);
        internal delegate void glGetVertexArrayIndexed64ivDelegate(uint vaobj, uint index, uint pname, Int64[] param);
        internal delegate void glCreateSamplersDelegate(int n, uint[] samplers);
        internal delegate void glCreateProgramPipelinesDelegate(int n, uint[] pipelines);
        internal delegate void glCreateQueriesDelegate(uint target, int n, uint[] ids);
        internal delegate void glGetQueryBufferObjecti64vDelegate(uint id, uint buffer, uint pname, IntPtr offset);
        internal delegate void glGetQueryBufferObjectivDelegate(uint id, uint buffer, uint pname, IntPtr offset);
        internal delegate void glGetQueryBufferObjectui64vDelegate(uint id, uint buffer, uint pname, IntPtr offset);
        internal delegate void glGetQueryBufferObjectuivDelegate(uint id, uint buffer, uint pname, IntPtr offset);
        internal delegate void glMemoryBarrierByRegionDelegate(uint barriers);
        internal delegate void glGetTextureSubImageDelegate(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, uint format, uint type, int bufSize, IntPtr pixels);
        internal delegate void glGetCompressedTextureSubImageDelegate(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int bufSize, IntPtr pixels);
        internal delegate uint glGetGraphicsResetStatusDelegate();
        internal delegate void glGetnCompressedTexImageDelegate(uint target, int lod, int bufSize, IntPtr pixels);
        internal delegate void glGetnTexImageDelegate(uint target, int level, uint format, uint type, int bufSize, IntPtr pixels);
        internal delegate void glGetnUniformdvDelegate(uint program, uint location, int bufSize, double[] @params);
        internal delegate void glGetnUniformfvDelegate(uint program, uint location, int bufSize, float[] @params);
        internal delegate void glGetnUniformivDelegate(uint program, uint location, int bufSize, int[] @params);
        internal delegate void glGetnUniformuivDelegate(uint program, uint location, int bufSize, uint[] @params);
        internal delegate void glReadnPixelsDelegate(int x, int y, int width, int height, uint format, uint type, int bufSize, IntPtr data);
        internal delegate void glGetnMapdvDelegate(uint target, uint query, int bufSize, double[] v);
        internal delegate void glGetnMapfvDelegate(uint target, uint query, int bufSize, float[] v);
        internal delegate void glGetnMapivDelegate(uint target, uint query, int bufSize, int[] v);
        internal delegate void glGetnPixelMapfvDelegate(uint map, int bufSize, float[] values);
        internal delegate void glGetnPixelMapuivDelegate(uint map, int bufSize, uint[] values);
        internal delegate void glGetnPixelMapusvDelegate(uint map, int bufSize, ushort[] values);
        internal delegate void glGetnPolygonStippleDelegate(int bufSize, byte[] pattern);
        internal delegate void glGetnColorTableDelegate(uint target, uint format, uint type, int bufSize, IntPtr table);
        internal delegate void glGetnConvolutionFilterDelegate(uint target, uint format, uint type, int bufSize, IntPtr image);
        internal delegate void glGetnSeparableFilterDelegate(uint target, uint format, uint type, int rowBufSize, IntPtr row, int columnBufSize, IntPtr column, IntPtr span);
        internal delegate void glGetnHistogramDelegate(uint target, bool reset, uint format, uint type, int bufSize, IntPtr values);
        internal delegate void glGetnMinmaxDelegate(uint target, bool reset, uint format, uint type, int bufSize, IntPtr values);
        internal delegate void glTextureBarrierDelegate();
    }
}
